name: Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Medify site
        run: curl -s -o /dev/null -w "%{http_code}" https://medify-pro-zeta.vercel.app
